### ISSUE TITLE
额……这是什么

### ISSUE THREAD

**Issue by SmallOyster** [zhangjingye03/ZJYHOME_network_test#1]
RT

**Comment by zhangjingye03** [comment]
网络实验的拓扑图

**Comment by SmallOyster** [comment]
没听过……

能具体说说嘛？

这是你家的什么？！

**Comment by zhangjingye03** [comment]
网络图啊

有些东西你还没有必要了解... :joy:

**Comment by SmallOyster** [comment]
……你家还搞网络……

**Comment by zhangjingye03** [comment]
兴趣爱好嘛
编程什么的太累了，偶尔玩玩网络

**Comment by SmallOyster** [comment]
@zhangjingye03
学长能不能具体说说这是干嘛的 :joy:
我蠢我不懂 :joy:
就是在你家干嘛？

**Comment by zhangjingye03** [comment]
..............
说太多你也不懂
只是在我家里的5台路由上运行BGP做实验
方便以后去考CCNA

**Comment by SmallOyster** [comment]
好吧……
但我还是想问问你家有多大？
需要用到五台路由器？
而且你的路由器是用来做WiFi还是什么……干啥用

**Comment by zhangjingye03** [comment]
100平米
给别人蹭网用，顺便自己做路由和网络安全的研究
